import Head from "next/head";
import LeftLine from "../components/LeftLine";
import Navbar from "../components/Navbar";
import PageHeader from "../components/PageHeader";

function About() {
  return (
    <div>
      <Navbar />
      <Head>
        <title>Beauty By Alexa | About</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <LeftLine />
        <section>
          <PageHeader title={"About"} info={"this is the about page"} />
        </section>
      </main>
    </div>
  );
}

export default About;
