import Head from "next/head";
import { useEffect } from "react";
import { BookingsApi, Client } from "square";
import LeftLine from "../components/LeftLine";
import Navbar from "../components/Navbar";
import PageHeader from "../components/PageHeader";
import ScheduleStep from "../components/Step";

function Schedule() {
  return (
    <div>
      <Head>
        <title>Beauty By Alexa | Schedule</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      <main>
        <LeftLine />
        <section className="text-custom-black">
          <PageHeader title={"Schedule"} />
          <div className="text-center mt-4">
            <p>
              <strong>You will be redirected to Schedulicity</strong> to
              schedule your appointment with Alexa!
            </p>
            <p className="mt-3">Please follow the steps below</p>
          </div>

          <div className="mt-10 space-y-2">
            <ScheduleStep
              number={1}
              info={
                <p>
                  Click on a drop down menu that displays{" "}
                  <strong>&quot;All Providers&quot;</strong>
                </p>
              }
            />
            <ScheduleStep
              number={2}
              info={
                <p>
                  Select <strong>&quot;Alexa&quot;</strong>
                </p>
              }
            />
            <ScheduleStep
              number={3}
              info={
                <p>
                  Click <strong>&quot;Add to visit&quot;</strong> for your
                  desired service.
                </p>
              }
            />
            <ScheduleStep
              number={4}
              info={
                <p>
                  Select <strong>&quot;Alexa&quot;</strong> as a provider.
                </p>
              }
            />
            <ScheduleStep
              number={5}
              info={
                <p>
                  Click <strong>&quot;Choose date and time&quot;</strong> to
                  schedule
                </p>
              }
            />
          </div>
        </section>
      </main>
    </div>
  );
}

export default Schedule;
