import Head from "next/head";
import LeftLine from "../components/LeftLine";
import Navbar from "../components/Navbar";
import PageHeader from "../components/PageHeader";

function Schedule() {
  return (
    <div>
      <Head>
        <title>Beauty By Alexa | Schedule</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      <main>
        <LeftLine />
        <section>
          <PageHeader title={"Schedule"} info={"schedule here"} />
        </section>
      </main>
    </div>
  );
}

export default Schedule;
